name: cimc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pip
  - pytorch
  - cuda91
  - torchvision
  - numpy
  - numba
  - pillow
  - pip:
    - git+https://gitlab.com/EAVISE/brambox
    - git+https://gitlab.com/EAVISE/lightnet
    - aiofiles
    - aiohttp
    - aiostream
    - coloredlogs
    - tqdm
    - imageio
    - opencv-contrib-python
    - scipy
    - scikit-learn
    - visdom
    - vispy
    - filterpy
