name: cimc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pkgs/main::python=3.6
  - pkgs/main::pip
  - pytorch::pytorch
  - pytorch::cuda91
  - pytorch::torchvision
  - numpy
  - numba
  - pillow
  - pip:
    - git+https://gitlab.com/EAVISE/brambox@master#egg=brambox
    - git+https://gitlab.com/EAVISE/lightnet@master#egg=lightnet
    - aiofiles
    - aiohttp
    - aiostream
    - coloredlogs
    - tqdm
    - imageio
    - opencv-contrib-python
    - scipy
    - scikit-learn
    - visdom
    - vispy
    - filterpy
